version: '3.8'
services:
  app:
    container_name: arch-docker-project
    image: arch-docker-project
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - PORT=3000
      - MONGO_DATABASE=adm
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
volumes:
  db: